# Generated by Django 5.2.2 on 2025-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_answer_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
