# Generated by Django 5.2.1 on 2025-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_hashtag_question_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
