# Generated by Django 5.2.1 on 2025-07-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
